
import java.awt.event.ActionListener;
import java.io.*;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import static sun.util.calendar.CalendarUtils.mod;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fabien
 */
public class Fenetre extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTParcourir = new javax.swing.JButton();
        BTraduire = new javax.swing.JButton();
        Titre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LBParcourir = new javax.swing.JLabel();
        LBLangue = new javax.swing.JLabel();
        RBFrancais = new javax.swing.JRadioButton();
        RBMorse = new javax.swing.JRadioButton();
        BTSupprimer = new javax.swing.JButton();
        LBAlphabet = new javax.swing.JLabel();
        LBMorse = new javax.swing.JLabel();
        TFMorse = new javax.swing.JTextField();
        TFAlphabet = new javax.swing.JTextField();
        BTAjouter = new javax.swing.JButton();
        CBSelectionner = new javax.swing.JComboBox();
        TFRecherche = new javax.swing.JTextField();
        BTRecherche = new javax.swing.JButton();
        LBSelectionner = new javax.swing.JLabel();
        LBRechercher = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        LBDictionnaire = new javax.swing.JLabel();
        BTCharger = new javax.swing.JButton();
        TAConsole = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTParcourir.setText("Parcourir");
        BTParcourir.setEnabled(false);
        BTParcourir.addActionListener(this);

        BTraduire.setText("Traduire");
        BTraduire.setEnabled(false);

        Titre.setFont(new java.awt.Font("Coolvetica", 1, 24)); // NOI18N
        Titre.setText("Traducteur Morse");

        LBParcourir.setText("Fichier à traduire");
        LBParcourir.setEnabled(false);

        LBLangue.setText("Langue ");
        LBLangue.setEnabled(false);

        RBFrancais.setSelected(true);
        RBFrancais.setText("vers français");
        RBFrancais.setEnabled(false);

        RBMorse.setText("vers morse");
        RBMorse.setEnabled(false);

        BTSupprimer.setText("Supprimer");
        BTSupprimer.setEnabled(false);

        LBAlphabet.setText("Alphabet");
        LBAlphabet.setEnabled(false);

        LBMorse.setText("Morse");
        LBMorse.setEnabled(false);

        TFMorse.setText("...........");
        TFMorse.setEnabled(false);

        TFAlphabet.setText("...........");
        TFAlphabet.setEnabled(false);

        BTAjouter.setText("Ajouter");
        BTAjouter.setEnabled(false);

        CBSelectionner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBSelectionner.setEnabled(false);

        TFRecherche.setText("jTextField3");
        TFRecherche.setEnabled(false);

        BTRecherche.setText("Lancer");
        BTRecherche.setEnabled(false);

        LBSelectionner.setText("Sélectionner");
        LBSelectionner.setEnabled(false);

        LBRechercher.setText("Rechercher");
        LBRechercher.setEnabled(false);

        jSeparator3.setEnabled(false);

        LBDictionnaire.setText("Ajouter votre dictionnaire");

        BTCharger.setText("Charger");
        BTCharger.addActionListener(this);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        TAConsole.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Titre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBDictionnaire)
                                .addGap(30, 30, 30)
                                .addComponent(BTCharger)
                                .addGap(149, 149, 149))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LBParcourir)
                                .addGap(18, 18, 18)
                                .addComponent(BTParcourir)
                                .addGap(30, 30, 30)
                                .addComponent(LBLangue)
                                .addGap(18, 18, 18)
                                .addComponent(RBFrancais)
                                .addGap(18, 18, 18)
                                .addComponent(RBMorse)
                                .addGap(27, 27, 27)
                                .addComponent(BTraduire)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBMorse)
                            .addComponent(LBAlphabet)
                            .addComponent(LBSelectionner)
                            .addComponent(LBRechercher))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBSelectionner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TFAlphabet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addComponent(TFMorse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTAjouter)
                            .addComponent(BTRecherche)
                            .addComponent(BTSupprimer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(TAConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titre)
                    .addComponent(LBDictionnaire)
                    .addComponent(BTCharger))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBParcourir)
                    .addComponent(LBLangue)
                    .addComponent(RBFrancais)
                    .addComponent(RBMorse)
                    .addComponent(BTraduire)
                    .addComponent(BTParcourir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(BTAjouter))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTRecherche)
                                    .addComponent(LBRechercher))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CBSelectionner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTSupprimer)
                                    .addComponent(LBSelectionner))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBMorse)
                                    .addComponent(TFMorse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBAlphabet)
                                    .addComponent(TFAlphabet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TAConsole)))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == BTParcourir) {
            Fenetre.this.BTParcourirActionPerformed(evt);
        }
        else if (evt.getSource() == BTCharger) {
            Fenetre.this.BTChargerActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void BTParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTParcourirActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Choisir un fichier texte");
        //Creer un filtre qui ne sélectionnera que les fichiers .txt
        FileNameExtensionFilter ff = new FileNameExtensionFilter("Fichiers texte", "txt");
        fc.setFileFilter(ff);

        int returnVal = fc.showOpenDialog(this);
        String nomFic = "Erreur fichier invalide";
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            nomFic = fc.getSelectedFile().getName();
            try {
                InputStream ips = new FileInputStream(nomFic);
                InputStreamReader ipsr = new InputStreamReader(ips);
                BufferedReader br = new BufferedReader(ipsr);
                String ligne;
                while ((ligne = br.readLine()) != null) {
                    jTextArea1.setText(ligne);
                }
                br.close();
            } catch (Exception e) {
                jTextArea1.setText(e.toString());
            }
        }
    }//GEN-LAST:event_BTParcourirActionPerformed

    private void BTChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTChargerActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Choisir un fichier Dictionnaire");
        //Creer un filtre qui ne sélectionnera que les fichiers .txt
        FileNameExtensionFilter ff = new FileNameExtensionFilter("Fichiers dictionnaire", "ini");
        fc.setFileFilter(ff);

        int returnVal = fc.showOpenDialog(this);
        String nomFic = "Erreur fichier invalide";
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            nomFic = fc.getSelectedFile().getName();
            jTextArea1.setText("Fichier dictionnaire chargé : " + nomFic);
            BTAjouter.setEnabled(true);
        }
    }//GEN-LAST:event_BTChargerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAjouter;
    private javax.swing.JButton BTCharger;
    private javax.swing.JButton BTParcourir;
    private javax.swing.JButton BTRecherche;
    private javax.swing.JButton BTSupprimer;
    private javax.swing.JButton BTraduire;
    private javax.swing.JComboBox CBSelectionner;
    private javax.swing.JLabel LBAlphabet;
    private javax.swing.JLabel LBDictionnaire;
    private javax.swing.JLabel LBLangue;
    private javax.swing.JLabel LBMorse;
    private javax.swing.JLabel LBParcourir;
    private javax.swing.JLabel LBRechercher;
    private javax.swing.JLabel LBSelectionner;
    private javax.swing.JRadioButton RBFrancais;
    private javax.swing.JRadioButton RBMorse;
    private javax.swing.JScrollPane TAConsole;
    private javax.swing.JTextField TFAlphabet;
    private javax.swing.JTextField TFMorse;
    private javax.swing.JTextField TFRecherche;
    private javax.swing.JLabel Titre;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
